const PostOrderOffers = {
  "body": {
    "type": "object",
    "properties": {
      "order_id": {
        "type": "integer",
        "description": "The Vrio Order ID returned when creating an order."
      },
      "offers": {
        "type": "array",
        "description": "Define the offers and Items to be used on the order. Use an array if adding multiple Item and Offer combinations.",
        "items": {
          "title": "OrderOfferPost",
          "type": "object",
          "required": [
            "offer_id",
            "order_offer_quantity"
          ],
          "properties": {
            "id": {
              "type": "string",
              "description": "A unique identifier for the particular offer for the order. This value is generated by you and used to allow orders to have the same offer on an order more than once."
            },
            "offer_id": {
              "type": "integer",
              "description": "Offer ID associated with offer."
            },
            "order_offer_quantity": {
              "type": "integer",
              "description": "The quantity of the offer."
            },
            "item_id": {
              "type": "integer",
              "description": "Vrio item id to be used with the offer_id. Required for shared offers."
            },
            "order_offer_price": {
              "type": "string",
              "description": "Override the configured offer price with a different price that will be used on the initial charge.",
              "pattern": "^\\d*(\\.\\d{0,2})?$"
            },
            "order_offer_shipping": {
              "type": "string",
              "description": "Override the configured offer level shipping price with a different price that will be used on the initial charge.",
              "pattern": "^\\d*(\\.\\d{0,2})?$"
            },
            "discount_code": {
              "type": "string",
              "description": "Discount code to be applied to this offer."
            },
            "order_offer_item_options": {
              "type": "array",
              "description": "When an Item has options, or variants, determine which options should be applied. Each option will have a subset option value. Example: size is an option, Small - Medium - Large is the option value. Required for items that have options.",
              "uniqueItems": true,
              "items": {
                "title": "ItemOption",
                "type": "object",
                "description": "When an Item has options, or variants, determine which options should be applied. Each option will have a subset option value. Example: size is an option, Small - Medium - Large is the option value.",
                "properties": {
                  "item_option_id": {
                    "type": "integer",
                    "description": "The option to be applied to the item."
                  },
                  "item_option_value_id": {
                    "type": "integer",
                    "description": "The value to be used for the item option ID passed."
                  }
                },
                "required": [
                  "item_option_id",
                  "item_option_value_id"
                ]
              }
            },
            "override_initial_item_id": {
              "type": [
                "integer",
                "null"
              ],
              "description": "Pass an Item ID that will be used for the initial only, ths order will then use the item_id passed for all subsequent transactions. See here for additional use cases."
            },
            "override_initial_item_options": {
              "type": "array",
              "description": "When  using an override_initial_item_id and the item has options, or variants, determine which options should be applied. Each option will have a subset option value. Required with override item has options.",
              "items": {
                "title": "OverrideItemOption",
                "type": "object",
                "properties": {
                  "item_option_id": {
                    "type": "integer",
                    "description": "The option to be applied to the override_initial_item_id."
                  },
                  "item_option_value_id": {
                    "type": "integer",
                    "description": "The value to be used for the override_initial_item_id."
                  }
                },
                "required": [
                  "item_option_id",
                  "item_option_value_id"
                ]
              }
            },
            "order_offer_upsell": {
              "type": "boolean",
              "description": "Mark true if this order offer should be flagged as an upsell. This is important for reporting."
            },
            "order_offer_upsell_weight": {
              "type": "integer",
              "description": "This can be used to define the order of upsell. Pass 1 for the first upsell, 2 for the second, etc."
            },
            "parent_order_offer_id": {
              "type": "integer",
              "description": "The parent_order_offer_id is referencing the specific order offer that the upsell was derived from. This would be available if an order was created and an offer was added to it, then you wanted to add an offer to it at a later date. Required when passing order_offer_upsell and not passing a parent_offer_id and parent_order_id."
            },
            "parent_offer_id": {
              "type": "integer",
              "description": "The parent_offer_id is what is passed when the parent_order_offer_id is not available. This would commonly be used when you create an order all at one time.. Required when passing order_offer_upsell and not passing a parent_order_offer_id."
            },
            "parent_order_id": {
              "type": "integer",
              "description": "The id of the original order, used to add an order offer as upsell from a different order.. Required when passing order_offer_upsell and not passing a parent_order_offer_id."
            },
            "status_type_id": {
              "type": [
                "integer",
                "null"
              ],
              "enum": [
                null,
                7,
                8
              ],
              "description": "This can be used to define the status of an upsell. If not passed, Vrio will define statuses. Accepted values are : \n* `7` - Rejected\n* `8` - Removed "
            },
            "is_gift": {
              "type": "boolean",
              "description": "If true, gift logic will apply to this order."
            },
            "gift_message": {
              "type": "string",
              "description": "Message to use for gift communication. Required if is_gift is true."
            },
            "gift_date": {
              "type": "string",
              "description": "Date to send gift communication. Required if is_gift is true."
            },
            "gift_name": {
              "type": "string",
              "description": "Name for the person receiving the gift. Required if is_gift is true."
            },
            "gift_email": {
              "type": "string",
              "description": "Email for the person receiving the gift. Required if is_gift is true."
            },
            "gift_phone": {
              "type": "string",
              "description": "Phone for the person receiving the gift. Required if is_gift is true."
            }
          }
        }
      }
    },
    "required": [
      "order_id",
      "offers"
    ],
    "$schema": "http://json-schema.org/draft-04/schema#"
  },
  "response": {
    "200": {
      "title": "Order Offers",
      "type": "object",
      "properties": {
        "order_offers": {
          "type": "array",
          "items": {
            "title": "Order Offer",
            "type": "object",
            "properties": {
              "order_offer_id": {
                "type": "integer"
              },
              "connection_order_offer_id": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "status_type_id": {
                "type": [
                  "integer",
                  "null"
                ],
                "title": "Status types",
                "enum": [
                  null,
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10
                ],
                "description": "* `1` - Active\n* `2` - Cancelled\n* `3` - Complete\n* `4` - Partial\n* `5` - Declined\n* `6` - Archive\n* `7` - Rejected\n* `8` - Removed\n* `9` - Paused\n* `10` - Expired\n\n`null` `1` `2` `3` `4` `5` `6` `7` `8` `9` `10`"
              },
              "linked_status_type_id": {
                "type": [
                  "integer",
                  "null"
                ],
                "title": "Status types",
                "enum": [
                  null,
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10
                ],
                "description": "* `1` - Active\n* `2` - Cancelled\n* `3` - Complete\n* `4` - Partial\n* `5` - Declined\n* `6` - Archive\n* `7` - Rejected\n* `8` - Removed\n* `9` - Paused\n* `10` - Expired\n\n`null` `1` `2` `3` `4` `5` `6` `7` `8` `9` `10`"
              },
              "date_cancel": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time",
                "examples": [
                  "2023-04-01 00:00:00"
                ]
              },
              "date_created": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time",
                "examples": [
                  "2023-04-01 00:00:00"
                ]
              },
              "date_modified": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time",
                "examples": [
                  "2023-04-01 00:00:00"
                ]
              },
              "date_ordered": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time",
                "examples": [
                  "2023-04-01 00:00:00"
                ]
              },
              "date_reactivate": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time",
                "examples": [
                  "2023-04-01 00:00:00"
                ]
              },
              "date_pause": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time",
                "examples": [
                  "2023-04-01 00:00:00"
                ]
              },
              "date_unpause": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time",
                "examples": [
                  "2023-04-01 00:00:00"
                ]
              },
              "is_gift": {
                "type": "boolean"
              },
              "is_recurring": {
                "type": "boolean"
              },
              "is_test": {
                "type": "boolean"
              },
              "offer_id": {
                "type": "integer"
              },
              "offer_name": {
                "type": "string"
              },
              "order_id": {
                "type": "integer"
              },
              "order_offer_price": {
                "type": "string",
                "pattern": "^\\d*(\\.\\d{0,2})?$",
                "default": "0.00"
              },
              "order_offer_quantity": {
                "type": "integer"
              },
              "cancel_type_id": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "cancel_by": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "discount_id": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "order_offer_upsell": {
                "type": "boolean"
              },
              "parent_order_offer_id": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "charge_timeframe_id": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "charge_timeframe_name": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "offer_cycle_multiple_shipments_count": {
                "type": "integer"
              },
              "fulfillment_delay_timeframe_id": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "total_shipments_count": {
                "type": "integer"
              },
              "shipped_shipments_count": {
                "type": "integer"
              },
              "current_shipment_prepaid_cycle": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "current_shipment_id": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "connection_status_type_name": {
                "type": "string"
              },
              "last_recurring_date": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time",
                "examples": [
                  "2023-04-01 00:00:00"
                ]
              },
              "last_recurring_amount": {
                "type": "string",
                "pattern": "^\\d*(\\.\\d{0,2})?$",
                "default": "0.00"
              },
              "next_recurring_date": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time",
                "examples": [
                  "2023-04-01 00:00:00"
                ]
              },
              "next_recurring_amount": {
                "type": "string",
                "pattern": "^\\d*(\\.\\d{0,2})?$",
                "default": "0.00"
              },
              "next_recurring_price": {
                "type": "string",
                "pattern": "^\\d*(\\.\\d{0,2})?$",
                "default": "0.00"
              },
              "next_recurring_charge": {
                "type": [
                  "integer",
                  "null"
                ]
              },
              "next_recurring_last_four": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "extra_fields": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "order_offer_notes": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "order_offer_shipments": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "shipment_id": {
                      "type": "integer"
                    },
                    "connection_shipment_id": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "customer_id": {
                      "type": "integer"
                    },
                    "order_id": {
                      "type": "integer"
                    },
                    "shipment_prepaid_cycle": {
                      "type": "integer"
                    },
                    "shipment_status_id": {
                      "type": "integer",
                      "title": "Shipment Status",
                      "enum": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9
                      ],
                      "description": "* `1` - Pending Post\n* `2` - Pending Tracking\n* `3` - Cancelled\n* `4` - Shipped\n* `5` - Error\n* `6` - Delivered\n* `7` - Declined\n* `8` - Pending Transaction\n* `9` - Skipped\t\n\n`1` `2` `3` `4` `5` `6` `7` `8` `9`"
                    },
                    "transaction_charge_id": {
                      "type": "integer"
                    },
                    "connection_id": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "fulfillment_id": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "shipment_tracking_id": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "carrier_id": {
                      "type": [
                        "integer",
                        "null"
                      ],
                      "title": "Carriers",
                      "enum": [
                        null,
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        8,
                        9
                      ],
                      "description": "* `1` - USPS\n* `2` - UPS\n* `3` - FedEx\n* `4` - DHL eCommerce\n* `5` - UPS Mail Innovations\n* `6` - Canada Post\n* `8` - Australia Post\n* `9` - Hermes\n\n`null` `1` `2` `3` `4` `5` `6` `8` `9`"
                    },
                    "shipping_profile_id": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "date_cancel": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "date_scheduled": {
                      "type": "string",
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "date_complete": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "date_scan": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "date_deliver": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "date_return": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "date_skip": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "date_rma": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "shipment_rma": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "cancel_type_id": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "skip_type_id": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "shipping_reship_type_id": {
                      "type": [
                        "integer",
                        "null"
                      ],
                      "title": "Shipping reship types",
                      "enum": [
                        null,
                        1,
                        2,
                        3,
                        4
                      ],
                      "description": "* `1` - Did not receive package\n* `2` - Damaged Items\n* `3` - Items Incorrect\n* `4` - Quantity Incorrect\n\n`null` `1` `2` `3` `4`"
                    },
                    "shipment_parent_type_id": {
                      "type": [
                        "integer",
                        "null"
                      ],
                      "title": "Shipment parent types",
                      "enum": [
                        null,
                        1,
                        2,
                        3,
                        4
                      ],
                      "description": "* `1` - Reship\n* `2` - Reward\n* `3` - Gift\n* `4` - Free\n\n`null` `1` `2` `3` `4`"
                    },
                    "date_created": {
                      "type": "string",
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "created_by": {
                      "type": "integer"
                    },
                    "date_modified": {
                      "type": "string",
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "modified_by": {
                      "type": "integer"
                    },
                    "shipment_notes": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "connection_request_text": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "connection_response_text": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "shipment_items": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "shipment_item_id": {
                            "type": "integer"
                          },
                          "quantity": {
                            "type": "integer"
                          },
                          "item_id": {
                            "type": "integer"
                          },
                          "item_name": {
                            "type": "string"
                          },
                          "item_description": {
                            "type": [
                              "string",
                              "null"
                            ]
                          },
                          "item_additional_description": {
                            "type": [
                              "string",
                              "null"
                            ]
                          },
                          "item_image": {
                            "type": [
                              "string",
                              "null"
                            ]
                          },
                          "shipment_item_sku": {
                            "type": [
                              "string",
                              "null"
                            ]
                          },
                          "items_option_variation_id": {
                            "type": [
                              "integer",
                              "null"
                            ]
                          }
                        }
                      }
                    }
                  }
                }
              },
              "order_offer_items": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "item_id": {
                      "type": "integer"
                    },
                    "item_name": {
                      "type": "string"
                    },
                    "item_category_id": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "item_description": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_image": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_active": {
                      "type": "boolean"
                    },
                    "item_price": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "pattern": "^\\d*(\\.\\d{0,2})?$",
                      "default": "0.00"
                    },
                    "item_msrp": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "pattern": "^\\d*(\\.\\d{0,2})?$",
                      "default": "0.00"
                    },
                    "item_cost": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "pattern": "^\\d*(\\.\\d{0,2})?$",
                      "default": "0.00"
                    },
                    "item_shippable": {
                      "type": "boolean"
                    },
                    "item_sku": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_weight": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "pattern": "^\\d*(\\.\\d{0,2})?$",
                      "default": "0.00"
                    },
                    "item_upc": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_slug": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_quantity": {
                      "type": "integer"
                    },
                    "connection_id": {
                      "type": [
                        "integer",
                        "null"
                      ]
                    },
                    "out_of_stock_block": {
                      "type": "boolean"
                    },
                    "item_turnaround_time": {
                      "type": "integer"
                    },
                    "item_additional_description": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_ingredients": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_video": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_sales_page": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_perishable": {
                      "type": "boolean"
                    },
                    "item_tax_code": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_additional_details_1": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_additional_details_2": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_additional_details_3": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_additional_details_4": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "item_additional_details_5": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "date_created": {
                      "type": "string",
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "created_by": {
                      "type": "integer"
                    },
                    "date_modified": {
                      "type": "string",
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "modified_by": {
                      "type": "integer"
                    },
                    "item_notes": {
                      "type": [
                        "string",
                        "null"
                      ]
                    }
                  }
                }
              },
              "order_offer_gifts": {
                "type": "array",
                "items": {
                  "title": "Order Offer Gift",
                  "type": "object",
                  "properties": {
                    "order_offer_id": {
                      "type": "integer"
                    },
                    "gift_card_code": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "gift_name": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "gift_message": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "gift_email": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "gift_phone": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "gift_date": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "gift_date_sent": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "format": "date-time",
                      "examples": [
                        "2023-04-01 00:00:00"
                      ]
                    },
                    "gift_status": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "$schema": "http://json-schema.org/draft-04/schema#"
    },
    "400": {
      "type": "object",
      "properties": {
        "error": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "message": {
              "type": "string"
            }
          }
        }
      },
      "$schema": "http://json-schema.org/draft-04/schema#"
    },
    "401": {
      "type": "object",
      "properties": {
        "error": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "message": {
              "type": "string"
            }
          }
        }
      },
      "$schema": "http://json-schema.org/draft-04/schema#"
    },
    "403": {
      "type": "object",
      "properties": {
        "error": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "message": {
              "type": "string"
            }
          }
        }
      },
      "$schema": "http://json-schema.org/draft-04/schema#"
    },
    "500": {
      "type": "object",
      "properties": {
        "error": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "message": {
              "type": "string"
            }
          }
        }
      },
      "$schema": "http://json-schema.org/draft-04/schema#"
    }
  }
} as const;
export default PostOrderOffers
